# Homework 10:

For questions 1-4 use the orthologs.sqlite database we created in class (include the database in the directory with the homework when returning it to github).

__Exercise 1.__ Create a query that will return the gene name, cai value and sequence for all yeast genes with CAI values larger than 0.85.

In [2]:
import sqlite3 as sql
import pandas as pd
con = sql.connect("orthologs.sqlite")

In [5]:
data1 = pd.read_sql("SELECT gene_name, cai, seq FROM sequences, cai WHERE sequences.gene_name = cai.title AND cai > 0.85", con)
data1

   gene_name    CAI                                                seq
0    YAL038W  0.893  ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...
1    YBR118W  0.876  ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...
2    YGL030W  0.865  ATGGCCCCAGTTAAATCCCAAGAATCTATCAACCAAAAGTTGGCTT...
3    YGR192C  0.924  ATGGTTAGAGTTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
4    YGR254W  0.871  ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
5    YHR174W  0.892  ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
6    YJL052W  0.856  ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
7    YJL189W  0.915  ATGGCTGCTCAAAAGTCTTTCAGAATCAAGCAAAAAATGGCTAAGG...
8    YJR009C  0.905  ATGGTTAGAGTTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
9    YKL060C  0.869  ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...
10   YLR044C  0.904  ATGTCTGAAATTACTTTGGGTAAATATTTGTTCGAAAGATTAAAGC...
11   YLR061W  0.859  ATGGCCCCAAACACTTCCAGAAAGCAAAAGATTGCCAAGACCTTTA...
12   YLR110C  0.870  ATGCAATTTTCTACTGTCGCTTCTATCGCCGCTGTCGCCGCTGTCG...
13   YPR043W  0.872  ATGGCTAAAAGAACTAAGAAGGTTGGTATCACTGGTAAGTACGGTG...
14   YPR080W  0.871  ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...

__Exercise 2.__ Modify the query above to return the gene name in yeast, the gene names in the other three species, the cai value and the sequence for all yeat genes with a cai value larger that 0.8 and that have orthologs in the other three species.

In [13]:
data2 = pd.read_sql("SELECT orthologs.*, cai, seq FROM orthologs, sequences, cai WHERE sequences.gene_name = cai.title AND sequences.gene_name = orthologs.cerevisiae AND cai > 0.8", con)
data2

,cerevisiae,mikatae,paradoxus,bayanus,CAI,seq
0,YAL038W,133,366,146,0.893,ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...
1,YBR181C,575,1733,1653,0.846,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...
2,YCR012W,2014,2464,2653,0.815,ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGG...
3,YCR031C,1948,2539,2721,0.805,ATGTCTAACGTTGTTCAAGCTCGTGACAATTCCCAAGTTTTTGGTG...
4,YEL034W,5747,5869,6110,0.814,ATGTCTGACGAAGAACATACCTTTGAAACTGCTGACGCTGGTTCCT...
5,YGL123W,8023,8791,8164,0.801,ATGTCTGCTCCAGAAGCTCAACAACAAAAGAGAGGTGGTTTCGGTG...
6,YGL135W,8073,8842,8219,0.832,ATGTCTAAGATCACCTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
7,YGR254W,9167,9320,9559,0.871,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
8,YHL015W,9576,10453,23293,0.827,ATGTCTGACTTTCAAAAGGAAAAGGTTGAAGAACAAGAACAACAAC...
9,YHL033C,9483,10537,10119,0.842,ATGGCCCCAGGTAAGAAAGTCGCTCCAGCTCCATTCGGTGCTAAGT...
10,YHR174W,10272,9737,10953,0.892,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
11,YJL052W,12006,11467,7692,0.856,ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
12,YJL190C,11505,12007,12309,0.812,ATGACCAGATCTTCCGTTTTAGCTGATGCTTTGAATGCCATTAACA...
13,YJR123W,12651,12748,13807,0.838,ATGTCTGACACCGAAGCTCCAGTTGAAGTTCAAGAAGATTTCGAAG...
14,YKL060C,13447,13709,14543,0.869,ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...
15,YKL152C,13136,14038,14168,0.811,ATGCCAAAGTTAGTTTTAGTTAGACACGGTCAATCCGAATGGAACG...
16,YLR355C,15884,15522,16470,0.802,ATGTTGAGAACTCAAGCCGCCAGATTGATCTGCAACTCCCGTGTCA...
17,YML024W,16317,17429,17865,0.810,ATGGGTAGAGTTAGAACCAAGACCGTCAAGCGTGCTTCTAAGGCTT...
18,YOL039W,19423,20163,22682,0.804,ATGAAGTACTTAGCTGCTTACCTATTATTGAACGCTGCTGGTAACA...
19,YOL086C,19645,19978,22315,0.811,ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCC...
20,YOL120C,19772,19865,22100,0.812,ATGGGTATCGATCACACTTCCAAGCAACACAAGAGATCTGGTCACA...
21,YOR063W,19967,20560,22996,0.830,ATGTCTCACAGAAAGTACGAAGCACCACGTCACGGTCATTTAGGTT...
22,YOR369C,20601,21712,24125,0.844,ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTG...
23,YPL090C,21951,22560,25232,0.837,ATGAAGTTGAACATTTCTTACCCAGTTAACGGGTCTCAAAAGACCT...
24,YPL131W,21794,22413,25389,0.830,ATGGCTTTCCAAAAAGACGCTAAGTCCTCTGCTTACTCCTCTCGTT...
25,YPL220W,21446,22041,24818,0.821,ATGTCCAAGATCACTTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
26,YPR080W,22559,23137,25835,0.871,ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...

__Exercise 3.__ Perform the same query as above, but this time include the chromosome number of the gene in the output.

In [15]:
data3 = pd.read_sql("SELECT orthologs.*, chrom, cai, seq FROM orthologs, sequences, cai, gff WHERE sequences.gene_name = cai.title AND sequences.gene_name = orthologs.cerevisiae AND sequences.gene_name = gff.acc AND cai > 0.8", con)
data3

,cerevisiae,mikatae,paradoxus,bayanus,chrom,CAI,seq
0,YAL038W,133,366,146,chrI,0.893,ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...
1,YBR181C,575,1733,1653,chrII,0.846,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...
2,YCR012W,2014,2464,2653,chrIII,0.815,ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGG...
3,YCR031C,1948,2539,2721,chrIII,0.805,ATGTCTAACGTTGTTCAAGCTCGTGACAATTCCCAAGTTTTTGGTG...
4,YEL034W,5747,5869,6110,chrV,0.814,ATGTCTGACGAAGAACATACCTTTGAAACTGCTGACGCTGGTTCCT...
5,YGL123W,8023,8791,8164,chrVII,0.801,ATGTCTGCTCCAGAAGCTCAACAACAAAAGAGAGGTGGTTTCGGTG...
6,YGL135W,8073,8842,8219,chrVII,0.832,ATGTCTAAGATCACCTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
7,YGR254W,9167,9320,9559,chrVII,0.871,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
8,YHL015W,9576,10453,23293,chrVIII,0.827,ATGTCTGACTTTCAAAAGGAAAAGGTTGAAGAACAAGAACAACAAC...
9,YHL033C,9483,10537,10119,chrVIII,0.842,ATGGCCCCAGGTAAGAAAGTCGCTCCAGCTCCATTCGGTGCTAAGT...
10,YHR174W,10272,9737,10953,chrVIII,0.892,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
11,YJL052W,12006,11467,7692,chrX,0.856,ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
12,YJL190C,11505,12007,12309,chrX,0.812,ATGACCAGATCTTCCGTTTTAGCTGATGCTTTGAATGCCATTAACA...
13,YJR123W,12651,12748,13807,chrX,0.838,ATGTCTGACACCGAAGCTCCAGTTGAAGTTCAAGAAGATTTCGAAG...
14,YKL060C,13447,13709,14543,chrXI,0.869,ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...
15,YKL152C,13136,14038,14168,chrXI,0.811,ATGCCAAAGTTAGTTTTAGTTAGACACGGTCAATCCGAATGGAACG...
16,YLR355C,15884,15522,16470,chrXII,0.802,ATGTTGAGAACTCAAGCCGCCAGATTGATCTGCAACTCCCGTGTCA...
17,YML024W,16317,17429,17865,chrXIII,0.810,ATGGGTAGAGTTAGAACCAAGACCGTCAAGCGTGCTTCTAAGGCTT...
18,YOL039W,19423,20163,22682,chrXV,0.804,ATGAAGTACTTAGCTGCTTACCTATTATTGAACGCTGCTGGTAACA...
19,YOL086C,19645,19978,22315,chrXV,0.811,ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCC...
20,YOL120C,19772,19865,22100,chrXV,0.812,ATGGGTATCGATCACACTTCCAAGCAACACAAGAGATCTGGTCACA...
21,YOR063W,19967,20560,22996,chrXV,0.830,ATGTCTCACAGAAAGTACGAAGCACCACGTCACGGTCATTTAGGTT...
22,YOR369C,20601,21712,24125,chrXV,0.844,ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTG...
23,YPL090C,21951,22560,25232,chrXVI,0.837,ATGAAGTTGAACATTTCTTACCCAGTTAACGGGTCTCAAAAGACCT...
24,YPL131W,21794,22413,25389,chrXVI,0.830,ATGGCTTTCCAAAAAGACGCTAAGTCCTCTGCTTACTCCTCTCGTT...
25,YPL220W,21446,22041,24818,chrXVI,0.821,ATGTCCAAGATCACTTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
26,YPR080W,22559,23137,25835,chrXVI,0.871,ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...

__Exercise 4.__ Now generate a table with the number of genes per chromosome that have CAI larger than 0.5 and have orthologs in the other three yeast species.

In [23]:
data4 = pd.read_sql("SELECT chrom, count(gene_name) FROM orthologs, sequences, cai, gff WHERE sequences.gene_name = cai.title AND sequences.gene_name = orthologs.cerevisiae AND sequences.gene_name = gff.acc AND cai > 0.5 GROUP by chrom", con)
data4

      chrom  count(gene_name)
0      chrI                 3
1     chrII                12
2    chrIII                 2
3     chrIV                11
4     chrIX                 3
5      chrV                11
6     chrVI                 5
7    chrVII                16
8   chrVIII                 6
9      chrX                11
10    chrXI                 6
11   chrXII                11
12  chrXIII                 6
13   chrXIV                 5
14    chrXV                15
15   chrXVI                10

__Exercise 5:__ Use the yeast genome gff file that we downloaded in class.

Read about the gff format and write a script that will create a database table with all the yeast genes and chromosomes. GFF files have all the annotation for a genome. For simplicity in our table we are only interested in the lines of the GFF files that give the coordinates of the chromosomes, genes, and tRNA genes. Your table should have the following columns: `ID number, Chromosome number, Start Position, End Position, Strand, Feature, Description`.

All this information should be readily available from the gff file, with the exception of the ID number, which is given as the "ID" in the last column, and you will have to process it a little bit. Again, only include in your table the yeast protein coding genes, tRNA coding genes, and chromosomes. Your final table should have one row per gene for a total of 6,923 rows.

Note that the description of several genes, and even some gene names contain special HTML characters, like %20. To convert these to text you should use the `unquote()` function of the `urllib` package. Do that before trying to use your regular expressions.

In [52]:
from urllib.parse import unquote
import sqlite3 as sql


# Parses the ID and Description from the attributes column
def parse_attributes(attributes):
    attribute_dict = {}
    for attribute in attributes.split(';'):
        if '=' in attribute:
            key, value = attribute.split('=')
            attribute_dict[key] = value

    id_number = attribute_dict.get('ID', '')
    description = unquote(attribute_dict.get('Note', ''))

    return id_number, description


# Load the GFF file, skipping comments
gff_path = './saccharomyces_cerevisiae_R64-3-1_20210421.gff'
gff_data = pd.read_csv(
    gff_path,
    sep='\t',
    comment='#',
    header=None,
    names=['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attribute'],
    dtype={'start': str, 'end': str, 'score': str, 'strand': str, 'frame': str},
    low_memory=False
)


# Filter for desired features
features_of_interest = ['gene', 'tRNA_gene', 'chromosome']
filtered_data = gff_data[gff_data['feature'].isin(features_of_interest)].copy()


# Parse the ID and Description
attributes_parsed = filtered_data['attribute'].apply(parse_attributes)
filtered_data.loc[:, 'ID Number'] = attributes_parsed.apply(lambda x: x[0])
filtered_data.loc[:, 'Description'] = attributes_parsed.apply(lambda x: x[1])


# Create a new DataFrame with the specific columns
final_data = filtered_data[['ID Number', 'seqname', 'start', 'end', 'strand', 'feature', 'Description']]
final_data.columns = ['ID Number', 'Chromosome Number', 'Start Position', 'End Position', 'Strand', 'Feature', 'Description']


# Reset the index of the DataFrame, drop the old index, and ensure all numbers are of type int
final_data.reset_index(drop=True, inplace=True)
final_data.loc[:, 'Start Position'] = final_data['Start Position'].astype(int)
final_data.loc[:, 'End Position'] = final_data['End Position'].astype(int)
# final_data


# Connect to SQLite and write the DataFrame to a new table
con = sql.connect('orthologs.sqlite')
final_data.to_sql('gff_new', con, if_exists='replace', index=False)


# Confirm completion
print("Database table created successfully with", len(final_data), "rows.")

Database table created successfully with 6923 rows.